version: '2'

services:
  mariadb:
    image: mariadb
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle

  moodle:
    image: bitnami/moodle:3.10.4-debian-10-r6
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
      - PUID=998
      - PGID=100
    volumes:
      - ./moodle:/bitnami/moodle
      - ./moodledata:/bitnami/moodledata
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb

  catcher:
    build:
      context: ./node_catcher
      dockerfile: ./Dockerfile
    image: nodejs
    container_name: nodejs_catcher
    restart: unless-stopped
    ports:  
      - 9090:9090
    command: node index.js

